version: '3.4'

services:
  sample:
    image: ${DOCKER_REGISTRY-}sample
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: sample
    ports:
      - "5332:80"
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - TEMP_PATH=${TEMP_PATH}
      - HANGFIRE_CONNECTIONSTRING=${HANGFIRE_CONNECTIONSTRING}
      - HANGFIRE_USER=${HANGFIRE_USER}
      - HANGFIRE_PASSWORD=${HANGFIRE_PASSWORD}
      - QUEUE_NAME=${QUEUE_NAME}
    volumes:
      - /var/tmp/sample/:/app/temp